# Generated by Django 2.2.14 on 2020-07-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_hjgjgjg'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='jkhgkjhkh',
            field=models.TextField(blank=True, null=True),
        ),
    ]
