# Generated by Django 2.2.14 on 2020-07-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_customtext_jkhgkjhkh"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="hjgjgjg",),
    ]
