# Generated by Django 2.2.14 on 2020-07-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_customtext_hjgjgjg"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="jkhgkjhkh",),
    ]
