# Generated by Django 2.2.14 on 2020-07-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_remove_customtext_jkhgkjhkh"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="jkhgkjhkh",
            field=models.TextField(blank=True, null=True),
        ),
    ]
