# Generated by Django 2.2.14 on 2020-07-03 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0007_customtext_jkhgkjhkh"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="dfqeas",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customtext_dfqeas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="ergfwsd",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customtext_ergfwsd",
                to="home.HomePage",
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="ffgwerg",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customtext_ffgwerg",
                to="home.CustomText",
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="fgwtrhg",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
