# Generated by Django 2.2.14 on 2020-07-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200703_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jhghgjg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
